/**
 * Regenerates src/features/login/disposable-domains.generated.ts from the
 * upstream disposable-email-domains blocklist.
 *
 * Run with: bun run sync:disposable-domains [ref]
 *
 * The generated file is committed, so builds and tests never touch the network
 * and every list update lands as a reviewable diff.
 */
const SOURCE_REPOSITORY = 'https://github.com/disposable-email-domains/disposable-email-domains';
const ref = Bun.argv[2] ?? 'main';
const sourceUrl = `https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/${ref}/disposable_email_blocklist.conf`;

const outputPath = new URL(
  '../src/features/login/disposable-domains.generated.ts',
  import.meta.url,
);

/** A truncated or hijacked response must never silently shrink the blocklist. */
const MINIMUM_EXPECTED_DOMAINS = 5_000;

/** Lowercase, no scheme, no path, at least two labels, no trailing dot. */
const DOMAIN = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/;

/**
 * Matching walks label suffixes, so a single-label entry would blocklist an
 * entire TLD, and a mainstream provider would lock out most real users. Both
 * are upstream mistakes we refuse rather than ship.
 */
const NEVER_BLOCKABLE = new Set([
  'gmail.com',
  'googlemail.com',
  'outlook.com',
  'hotmail.com',
  'live.com',
  'yahoo.com',
  'icloud.com',
  'me.com',
  'proton.me',
  'protonmail.com',
  'aol.com',
  'yandex.ru',
  'mail.ru',
  'gmx.de',
  'web.de',
  'zoho.com',
]);

const response = await fetch(sourceUrl);
if (!response.ok) {
  throw new Error(`Failed to fetch ${sourceUrl}: HTTP ${response.status}`);
}

const domains = new Set<string>();
const rejected: string[] = [];

for (const line of (await response.text()).split('\n')) {
  const domain = line.trim().toLowerCase().replace(/\.+$/, '');
  if (domain.length === 0 || domain.startsWith('#')) continue;

  if (!DOMAIN.test(domain) || domain.length > 253) {
    rejected.push(`${domain} (not a valid multi-label domain)`);
    continue;
  }
  if (NEVER_BLOCKABLE.has(domain)) {
    rejected.push(`${domain} (mainstream provider)`);
    continue;
  }
  domains.add(domain);
}

if (rejected.length > 0) {
  throw new Error(
    `Refusing to generate a blocklist from ${rejected.length} unusable upstream entries:\n  ${rejected.join('\n  ')}`,
  );
}
if (domains.size < MINIMUM_EXPECTED_DOMAINS) {
  throw new Error(
    `Refusing to generate a blocklist of only ${domains.size} domains (expected at least ${MINIMUM_EXPECTED_DOMAINS})`,
  );
}

const sorted = [...domains].sort();
const file = `// @generated by scripts/sync-disposable-domains.ts — do not edit by hand.
// Source: ${SOURCE_REPOSITORY} (${ref}, disposable_email_blocklist.conf)
// Domains: ${sorted.length}
// Synced: ${new Date().toISOString().slice(0, 10)}
//
// Stored as newline-delimited text so updates diff one domain per line and the
// module parses as a single string rather than ${sorted.length} array literals.

export const generatedDisposableDomains: readonly string[] = \`
${sorted.join('\n')}
\`
  .trim()
  .split('\\n');
`;

await Bun.write(outputPath, file);
console.info(`Wrote ${sorted.length} disposable domains to ${outputPath.pathname}`);
